### ISSUE TITLE
Why in this way?

### ISSUE THREAD

**Issue by Jeremi360** [MaxIsJoe/GodotDialogueResourceSystem#1]
Why in this way?
I don't see way you think this is better than json - ti make more difficult to see which character is saying what if you have long dialog.
If you don't like json approach maybe try my [Rakugo](https://github.com/rakugoteam/Rakugo) project and join it development process - now I develop it by myself :(

**Comment by MaxIsJoe** [comment]
1-It's not better nor worse than JSON, I just simply don't like the JSON approach to dialogue like many others who were looking for a different way to display dialogue for their prototypes and wanted something that was simple but flexible 

2-It doesn't make it difficult at all, if you payed attention to how I structured it, Names and Strings must always have the same array size, The speaker's index always corresponds with his dialogue's string index in the arrays, if you leave a dot inside an index inside the names array the system will simply say "hey, there is no speaker here so hide the name's label" but it will display the string that's in the Strings array regardless

3-I'll definitely look into Rakugo and see how good it works
